### ISSUE TITLE
Help file example code error - rangemap_tsa.R

### ISSUE THREAD

**Issue by olifog** [marlonecobos/rangemap#17]
Error:
```
> tsa <- rangemap_tsa(occurrences = occ_g, region_of_interest = reg,
+                     threshold = thr, resolution = res, save_shp = save,
+                     name = name)
Writing shapefiles in the working directory.
 Error in rgdal::writeOGR(clip_area, ".", name, driver = "ESRI Shapefile") : 
  layer exists, use a new layer name 
```

**Comment by olifog** [comment]
**Session info:**
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin18.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.7/lib/libopenblasp-r0.3.7.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rangemap_0.1.2 raster_3.0-7   maptools_0.9-9 sp_1.3-2       maps_3.3.0     rgbif_1.4.0

**Comment by marlonecobos** [comment]
Thanks @oliverfogelin,
See solution in issue #11
