### ISSUE TITLE
Help file example code error - rangemap_emaps.R

### ISSUE THREAD

**Issue by olifog** [marlonecobos/rangemap#18]
While running the example code for rangemap_emaps.R, I came across an error, due to the taxonKey specified returning 'no data found, try a different search' from occ. I continued on with the example code with a different key.

Error due to occ returning 'no data found, try a different search':
```
> occ_g <- occ[!is.na(occ$decimalLatitude) & !is.na(occ$decimalLongitude),
+             c("name", "decimalLongitude", "decimalLatitude")]
Error in occ$decimalLatitude : $ operator is invalid for atomic vectors
```

Although this isn't a fault of the library, the example code is still invalid- I'd recommend changing `key <- species$key[17]` to `key <- species$key[10]` to fix it.

**Comment by olifog** [comment]
**Session info:**
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin18.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.7/lib/libopenblasp-r0.3.7.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rangemap_0.1.2 raster_3.0-7   maptools_0.9-9 sp_1.3-2       maps_3.3.0     rgbif_1.4.0

**Comment by marlonecobos** [comment]
Thanks @oliverfogelin, 
See solution in issue #10
