### ISSUE TITLE
Create a Hex Logo for package

### ISSUE THREAD

**Issue by vijaybarve** [marlonecobos/rangemap#2]
It will be useful to have a Hex Logo for package.

**Comment by Jack-horwell** [comment]
I've created this as a hex logo, it was inspired by the maps that are produced by rangemap

![Hex logo (rangemap)](https://user-images.githubusercontent.com/36800721/70941663-d1538c80-2044-11ea-93a8-05062622a1d3.png)

Hope it is something like what you expected, feel free to suggest edits to the font or anything else

**Comment by Aaron-glitch-ass** [comment]
![Project - Drawing 1716684758](https://user-images.githubusercontent.com/58646959/71701106-8e463700-2e02-11ea-94c2-2872794414d0.png)

I don't know if this work

**Comment by adtserapio** [comment]
Hello Sirs @marlonecobos @vijaybarve ! Could you please advise me if this logo is suitable? I will also generate the SVG file if this PNG is appropriate for the bdvis package.

![Artboard 13x](https://user-images.githubusercontent.com/12228528/71757089-31b04e00-2ece-11ea-989d-90471e76b997.png)

**Comment by Aaron-glitch-ass** [comment]
> Hello Sirs @marlonecobos @vijaybarve ! Could you please advise me if this logo is suitable? I will also generate the SVG file if this PNG is appropriate for the bdvis package.

that's great! I will rather surrender if I see this logo (I am left speechless)

**Comment by Aaron-glitch-ass** [comment]
https://drive.google.com/open?id=1SkC61H_SASY9li7FLMId88gZ-yLlYRqJ

This is my improved logo @vijaybarve @marlonecobos 

Is it ok?

**Comment by marlonecobos** [comment]
Hi @Pilipino, your logo looks really good. Please attach an SVG file and a 181x209 PNG file.

**Comment by adtserapio** [comment]
[rangemap-logo.zip](https://github.com/marlonecobos/rangemap/files/4021564/rangemap-logo.zip)

Hello Sir @marlonecobos I have attached here the ZIP file containing the SVG file, 181 x 209 PNG file, and the 2" by 1.73" PNG file for the following Rangemap logo! :)

![ragemap-logo-181x209](https://user-images.githubusercontent.com/12228528/71760217-ecebdd80-2ef4-11ea-98c9-08c4956169bd.png)

**Comment by hxxr** [comment]
I have also created a logo. It splits the world map into multiple zones.
By the way, I checked, the R logo uses [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).
![Rangemap-1728x2000](https://user-images.githubusercontent.com/20031853/71772051-5a5a3700-2f12-11ea-9c42-5b7456ef9ed0.png)

[Here is a zip archive containing the high-definition PNG seen above as well as a 181x209 PNG version and the original SVG.](https://github.com/marlonecobos/rangemap/files/4022540/Rangemap.zip)

**Comment by hxxr** [comment]
I have also created a logo. It splits the world map into multiple zones.
The version seen here is in 1728x2000 pixel PNG format, rendered from a vector image created using Inkscape.
By the way, I checked, the R logo uses [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).
![Rangemap-1728x2000](https://user-images.githubusercontent.com/20031853/71772051-5a5a3700-2f12-11ea-9c42-5b7456ef9ed0.png)

[Here is a zip archive containing the high-definition PNG seen above as well as a 181x209 PNG version and the original SVG.](https://github.com/marlonecobos/rangemap/files/4022567/Rangemap.zip)

**Comment by hxxr** [comment]
Here is a lowercase version: [rangemap.zip](https://github.com/marlonecobos/rangemap/files/4022768/rangemap.zip)

![rangemap-1728x2000](https://user-images.githubusercontent.com/20031853/71773353-96e55d00-2f29-11ea-9220-ddce97febcdf.png)

**Comment by Aaron-glitch-ass** [comment]
https://drive.google.com/open?id=1rw6WLChkWB1GmT4T4Sp6Yb8ykc6mxQS7

**Comment by Aaron-glitch-ass** [comment]
i have just submitted to @vijaybarve

**Comment by Aaron-glitch-ass** [comment]
is it ok

**Comment by Aaron-glitch-ass** [comment]
https://drive.google.com/open?id=1hdb1d02alyIVnlDkf6pA-9B8EJNPOp6l

**Comment by Aaron-glitch-ass** [comment]
is it ok @Pilipino @vijaybarve @marlonecobos

**Comment by adtserapio** [comment]
@Aaron-glitch-ass Im just a participant too, but if I may advise, it would be necessary to use a hexagon logo format and use a vector illustration platform. My go-to is Illustrator, but you might want to use Gravit Designer instead.

**Comment by Aaron-glitch-ass** [comment]
> @Aaron-glitch-ass Im just a participant too, but if I may advise, it would be necessary to use a hexagon logo format and use a vector illustration platform. My go-to is Illustrator, but you might want to use Gravit Designer instead.

Gravit designer  is too expensive

**Comment by adtserapio** [comment]
@Aaron-glitch-ass I think there is a free version @ https://www.designer.io/en/pricing/

**Comment by Aaron-glitch-ass** [comment]
> @Aaron-glitch-ass I think there is a free version @ https://www.designer.io/en/pricing/

thanks for your advice! I appreciate it very much.

**Comment by Aaron-glitch-ass** [comment]
![Untitled gci](https://user-images.githubusercontent.com/58646959/71976424-3e77cd80-3251-11ea-9710-ca7df86d16f1.png)

@vijaybarve @Pilipino @marlonecobos

**Comment by Aaron-glitch-ass** [comment]
completed

**Comment by vansh0901** [comment]
![Uploading 2.png…]()

**Comment by vansh0901** [comment]
![1](https://user-images.githubusercontent.com/58524151/72220666-f02c3c80-3578-11ea-9e3c-0d78cd111ab9.png)

**Comment by vansh0901** [comment]
![2](https://user-images.githubusercontent.com/58524151/72220679-1eaa1780-3579-11ea-9d57-57b872808b8a.png)
