### ISSUE TITLE
statistical tests for overlap of species ranges

### ISSUE THREAD

**Issue by jrherr** [marlonecobos/rangemap#26]
Hello @marlonecobos

Thank you for your awesome package! I am working through it right now. 

This is not an issue, but I am wondering if you could provide some input -- I have ranges for two species. My hypothesis is one species may be a parasite of the other. The ranges appear to overlap. Do you know of a method (or R package) to statistically test this overlap using rangemap versus a null model or that by chance?

Thank you again! ~ Josh @jrherr

**Comment by marlonecobos** [comment]
Hi @jrherr, thanks for the kind words.

I think you can use ellipsenm as long as you have a good amount of good quality records and a clear idea of what are the accessible areas for both species. 

Other R packages that you can take a look at are ENMTools and ecospat, I think there is one called Humblot as well.  Those packages have options to measure niche overlap or similarity and are very well developed. Check which one of those suits you better considering what you need. Check the following videos, there are simple explanations of two of the packages I mentioned and ellipsenm there.

https://youtu.be/dNExVcExMAo
https://youtu.be/eigVVEsZT8E
https://youtu.be/id-O5UcIFF4

I hope it helps.

Edit:
All the ideas above are about comparisons of species ecological niches. Perhaps the most appropriate package for species range overlap is ENMTools; at least in a non-R version that I know you could compare species ranges there.

**Comment by jrherr** [comment]
Thank you so much for all your input, @marlonecobos! I truly appreciate your time! I am trying out those ideas now.
