### ISSUE TITLE
request: allow to set path when using save_shp in rangemap_hull

### ISSUE THREAD

**Issue by PietrH** [marlonecobos/rangemap#28]
Currently when saving shapefiles of calculated hulls, they are stored in the working directory. It would be nice if it were possible to set this path in the function call, instead of having to change the working directory to a data path and then back to the project directory. 

I'd be willing to give this change a go in a separate branch if you'd like?

**Comment by marlonecobos** [comment]
Hi, 
I agree. I have a version of the functions that does that already. Will be pushing it today night. Please install the package from GH to get these new version.

**Comment by marlonecobos** [comment]
This issue has been solved in the dev-version. Install from GitHub if needed.
