### ISSUE TITLE
Request: calculation of range area overlaps

### ISSUE THREAD

**Issue by gfgalbraith** [marlonecobos/rangemap#29]
Hi,

Thanks for the great work on this package! I was wondering if you had considered including a function to calculate pariwise comparisons of range area overlap? Either EOO or AOO.

A few earlier packages did this really well, albeit using other methods for calculating EOO,  but it was a really useful function.
https://rdrr.io/cran/letsR/man/lets.overlap.html
https://rdrr.io/cran/speciesgeocodeR/man/CoExClass.html

Would you consider adding this sort of function?
Thanks

**Comment by marlonecobos** [comment]
Hi, sorry for this late reply. I am not quite sure what do you mean by overlap. Do you mean a geographic grid where the presence-absence of multiple species is represented (PAM)?

If it is that, check the `biosurvey` package, particularly the functions related to PAMs. 
https://cran.r-project.org/package=biosurvey 

The outputs of `rangemap` could be used to create a PAM for a region using that package. Of course, considering that the `rangemap` outputs should be interpreted carefully as they are simple views of the species distrbution.

You can perform a series of analyses with the PAMs as well.  A guide here:
https://claununez.github.io/biosurvey/

Best,
