### ISSUE TITLE
Check execution of all help file example code

### ISSUE THREAD

**Issue by marlonecobos** [marlonecobos/rangemap#3]
Need a thorough checking on different systems

**Comment by Azamlynny** [comment]
I checked through all of the help file example code thoroughly and my observations are shown below:

Errors have been written their own issue with error message logs. 
Functioning example code that requires functions from other files have the functions and locations listed. 

### Help File Example Code Status 

**adm_area_names.R**     - Good
**country_codes.R**         - Good 
**rangemap.R**                - No help file example code
**rangemap_bound.R**    - Good - Requires functions north_arrow (rangemap_fig.R), rangemap_fig (rangemap_fig.R), rangemap_explore (rangemap_explore.R)
**rangemap_buff.R**       - Good - Requires functions rangemap_fig (rangemap_fig.R), rangemap_buff (rangemap_buff.R)
**rangemap_enm.R**      - Error - Issue #9	
**rangemap_explore.R**	- Error - Issue #6
**rangemap_fig.R**         - Error - Issue #5
**rangemap_hull.R**       - Error - Issue #4 	
**rangemap_tsa.R**        - Error - Issue #7
**ranges_emaps.R**        - Error - Issue #8 	
**ranges_espace.R**        - Good

### Session Info:
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maptools_0.9-9 maps_3.3.0     raster_3.0-7   sp_1.3-2       rgbif_1.4.0   

### Session Info:
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maptools_0.9-9 maps_3.3.0     raster_3.0-7   sp_1.3-2       rgbif_1.4.0   

<details><summary>loaded via a namespace (and not attached):</summary>
<p>
 [1] httr_1.4.1              
rnaturalearth_0.1.0    
 tidyr_1.0.0             
jsonlite_1.6           
 [5] viridisLite_0.3.0    
   shiny_1.4.0         
    assertthat_0.2.1
        triebeard_0.3.0        
 [9] urltools_1.7.3     
     yaml_2.2.0         
    pillar_1.4.2          
  backports_1.1.5        
[13] lattice_0.20-38  
       glue_1.3.1          
    digest_0.6.23        
   manipulateWidget_0.10.0
[17] promises_1.1.0   
       colorspace_1.4-1  
      htmltools_0.4.0 
        httpuv_1.5.2           
[21] plyr_1.8.4    
          pkgconfig_2.0.3 
        oai_0.3.0   
            httpcode_0.2.0         
[25] purrr_0.3.3   
          xtable_1.8-4    
        scales_1.1.0    
        webshot_0.5.2          
[29] whisker_0.4    
         later_1.0.0   
          tibble_2.1.3  
          spatial_7.3-11         
[33] farver_2.0.1     
       ggplot2_3.2.1  
         lazyeval_0.2.2 
         magrittr_1.5           
[37] crayon_1.3.4    
        mime_0.7       
         xml2_1.2.2      
        foreign_0.8-71         
[41] class_7.3-15   
         tools_3.6.1    
         data.table_1.12.6   
    lifecycle_0.1.0        
[45] stringr_1.4.0 
          V8_2.3       
           plotly_4.9.1  
          munsell_0.5.0          
[49] geoaxe_0.1.0    
        compiler_3.6.1  
        e1071_1.7-3    
         concaveman_1.0.0       
[53] rlang_0.4.2  
           classInt_0.4-2 
         units_0.6-5      
       grid_3.6.1             
[57] rstudioapi_0.10    
     htmlwidgets_1.5.1  
     crosstalk_1.0.0       
  miniUI_0.1.1.1         
[61] gtable_0.3.0      
      codetools_0.2-16   
     DBI_1.0.0          
     curl_4.2               
[65] R6_2.4.1         
       knitr_1.26       
       dplyr_0.8.3      
       rgdal_1.4-8            
[69] fastmap_1.0.1  
         rgeos_0.5-2      
       zeallot_0.1.0       
    KernSmooth_2.23-15     
[73] stringi_1.4.3      
     crul_0.9.0          
    Rcpp_1.0.3         
     vctrs_0.2.0            
[77] sf_0.8-0           
     rgl_0.100.30       
     tidyselect_0.2.5   
     xfun_0.11 
</p>
</details>

**Comment by marlonecobos** [comment]
Hi @Azamlynny, thanks for testing the code. I made the corrections needed and I am not getting new errors. I closed the other issues you posted, but I will leave this one open in case other student from GCI is interested in this task.

**Comment by olifog** [comment]
Hi! I went through all the help file example codes as well, since I'm on a different platform to the first student. Here are the errors I found:

# Errors
adm_area_names.R - None
country_codes.R - None
rangemap.R - No example
rangemap_bound.R - 1 error, not in library but in example code - Issue #10 
rangemap_buff.R - 1 error - Issue #11 
rangemap_enm.R - 1 error - Issue #12
rangemap_explore.R - 1 error, not in library but in example code - Issue #13
rangemap_fig.R - 1 error, not in library but in example code - Issue #14
rangemap_hull.R - 2 errors, 1 in example code - Issue #15 - one in library code - Issue #16
rangemap_tsa.R - 1 error - Issue #17
ranges_emaps.R - 1 error, not in library but in example code - Issue #18
ranges_espace.R - 1 error, not in library but in example code - Issue #19

# Session info
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin18.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.7/lib/libopenblasp-r0.3.7.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rangemap_0.1.2 raster_3.0-7   maptools_0.9-9 sp_1.3-2       maps_3.3.0     rgbif_1.4.0

**Comment by olifog** [comment]
The majority of my errors were just changing the taxonKey so that occ actually returned data. There are a few errors that are a bit more odd though- #11, #12, #16 and #17. These are all the same error, something to do with me running it on a mac maybe? I couldn't entirely figure out what was wrong.

**Comment by vijaybarve** [comment]
@oliverfogelin Thank you for the efforts, We will look into the issues.

**Comment by Jack-horwell** [comment]
I've checked the code and example code snippets and this is the outcome

adm_area_names.R - All good
country_codes.R - All good
rangemap.R - N/A
rangemap_bound.R - All good
rangemap_buff.R - All good
rangemap_enm.R - All good
rangemap_explore.R - All good
rangemap_fig.R - All good
rangemap_hull.R - Error: Issue #21
rangemap_tsa.R - All good
ranges_emaps.R - Error: Issue #22
ranges_espace.R - All good except in Rstudio the message "WebGL is not supported by your browser" appears, I am using chrome

### Session info
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] spocc_1.0.2    kuenm_1.1.3    raster_3.0-7   maptools_0.9-9 sp_1.3-2       maps_3.3.0     rgbif_1.4.0    rangemap_0.1.3 rgl_0.100.30  
[10] devtools_2.2.1 usethis_1.5.1

**Comment by marlonecobos** [comment]
Function rangemap_hull has been upgraded and the errors were fixed.
